[package]
name = "connectume"
version = "0.1.0"
authors = ["tomerhc <hacohen0tomer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.6.2"
regex = "1" 
byteorder = "1.3.4"
